name: Run my python

on: 
  push: # do this every push
  schedule:
  - cron: '30 2 * * *'  # Runs at 8 am Asia/Asia Central time
  
jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # what kind of github action version to use
    
    - name: Run my python
      run: |
        python3 Test_stockPrice_v3_20240323.py
        python3 Email_CSV_20240323.py


  
  
