name : Run my python
on : 
  push: # do this every time

jobs: 
  build:
    name: set up environment
    runs-on:  ubuntu-lastest
    steps:
      - uses:  action/checkout@test3
      - name:  Run my python
        run:
          python3 test.py




  
  
